name: ResidenceSQL
version: '${project.version}'
main: residencesql.residencesql.ResidenceSQL
api-version: 1.19
authors: [ siege260 ]
folia-supported: true
commands:
  createres:
  welcomemessage:
  addmember:
  removemember:
  removeresidence: